# Copyright (C) 2026 Radio Sound, Inc.
# SPDX-License-Identifier: Apache-2.0

flag_value {
    package: "android.media.audio"
    name: "foreground_audio_control"
    state: DISABLED
    permission: READ_ONLY
}
